/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createPACTEELDatabase = /* GraphQL */ `
  mutation CreatePACTEELDatabase($input: CreatePACTEELDatabaseInput!) {
    createPACTEELDatabase(input: $input) {
      CAS_Number
      Chemical_Formula
      Chemical_ID
      Chemical_Name
      Date
      Status
      UN_Number
      aegl1
      aegl2
      aegl3
      compoundAdjustmentFactor
      concentrationLimit
      eegl30
      eegl60
      element
      erpg1
      erpg2
      erpg3
      idlh
      isAsphyxiant
      isYChemical
      lc50
      lclo
      ld50
      ldlo
      loc
      makceiling
      makstel
      maktwa
      molecularWeight
      originalUnit
      pac1
      pac1Source
      pac2
      pac2Source
      pac3
      pac3Source
      pelceiling
      pelstel
      peltwa
      relceiling
      relstel
      reltwa
      tclo
      tdlo
      teel1
      teel1Source
      teel2
      teel2Source
      teel3
      teel3Source
      tlvstel
      tlvtwa
      weelceiling
      weelstel
      weeltwa
    }
  }
`;
export const deletePACTEELDatabase = /* GraphQL */ `
  mutation DeletePACTEELDatabase($input: DeletePACTEELDatabaseInput!) {
    deletePACTEELDatabase(input: $input) {
      CAS_Number
      Chemical_Formula
      Chemical_ID
      Chemical_Name
      Date
      Status
      UN_Number
      aegl1
      aegl2
      aegl3
      compoundAdjustmentFactor
      concentrationLimit
      eegl30
      eegl60
      element
      erpg1
      erpg2
      erpg3
      idlh
      isAsphyxiant
      isYChemical
      lc50
      lclo
      ld50
      ldlo
      loc
      makceiling
      makstel
      maktwa
      molecularWeight
      originalUnit
      pac1
      pac1Source
      pac2
      pac2Source
      pac3
      pac3Source
      pelceiling
      pelstel
      peltwa
      relceiling
      relstel
      reltwa
      tclo
      tdlo
      teel1
      teel1Source
      teel2
      teel2Source
      teel3
      teel3Source
      tlvstel
      tlvtwa
      weelceiling
      weelstel
      weeltwa
    }
  }
`;
export const updatePACTEELDatabase = /* GraphQL */ `
  mutation UpdatePACTEELDatabase($input: UpdatePACTEELDatabaseInput!) {
    updatePACTEELDatabase(input: $input) {
      CAS_Number
      Chemical_Formula
      Chemical_ID
      Chemical_Name
      Date
      Status
      UN_Number
      aegl1
      aegl2
      aegl3
      compoundAdjustmentFactor
      concentrationLimit
      eegl30
      eegl60
      element
      erpg1
      erpg2
      erpg3
      idlh
      isAsphyxiant
      isYChemical
      lc50
      lclo
      ld50
      ldlo
      loc
      makceiling
      makstel
      maktwa
      molecularWeight
      originalUnit
      pac1
      pac1Source
      pac2
      pac2Source
      pac3
      pac3Source
      pelceiling
      pelstel
      peltwa
      relceiling
      relstel
      reltwa
      tclo
      tdlo
      teel1
      teel1Source
      teel2
      teel2Source
      teel3
      teel3Source
      tlvstel
      tlvtwa
      weelceiling
      weelstel
      weeltwa
    }
  }
`;
